### ISSUE TITLE
gyp build error

### ISSUE THREAD

**Issue by donginssam** [therne/instauuid#1]
`npm install --save instauuid` 진행시 다음과 같은 오류가 발생합니다.
`g++: error: unrecognized command line option ‘-stdlib=libc++’`

gcc 와 컴파일 관련 패키지는 설치되어있습니다.

Node.js 버전 : 0.12.0
NPM 버전 : 2.5.1
node-gyp 버전 : 1.0.2
Linux 버전 : Ubuntu Server 14.04.1 LTS (3.13.0-36-generic x86_64)

**Comment by therne** [comment]
해결했습니다. 제보 감사합니다 :smiley:

**Comment by luismramirezr** [comment]
I'm getting the same error
